const menu = [
  {
    id: 1,
    title: "Butter Pancakes",
    category: "breakfast",
    price: 20.0,
    img: "./images/pancake.jpg",
    desc: "Fluffy butter pancakes served warm with a rich, melt-in-your-mouth flavor everyone loves.",
  },
  {
    id: 2,
    title: "Nutella Milkshake",
    category: "Milkshake",
    price: 12.99,
    img: "./images/nutella.jpg",
    desc: "Rich and creamy Nutella shake with a velvety chocolate-hazelnut flavor in every sip",
  },
  {
    id: 3,
    title: "Egg Toast",
    category: "breakfast",
    price: 15.99,
    img: "./images/eggtoast.jpg",
    desc: "Crispy egg toast with a soft, savory center, perfect for a simple and satisfying bite",
  },
  {
    id: 4,
    title: "Oreo Milkshake",
    category: "Milkshake",
    price: 10.3,
    img: "./images/oreo.jpg",
    desc: "Creamy Oreo milkshake blended to perfection with crunchy cookie bits in every sip.",
  },
  {
    id: 5,
    title: "Carrot Cake",
    category: "cake",
    price: 16.99,
    img: "./images/carrotcake.jpg",
    desc: "Moist and spiced carrot cake with a sweet cream cheese frosting, perfect for any occasion",
  },
  {
    id: 6,
    title: "French Toast",
    category: "breakfast",
    price: 25.0,
    img: "./images/frenchtoast.jpg",
    desc: "Golden, caramelized French toast made with thick bread slices and a hint of warm spice.",
  },
  {
    id: 7,
    title: "Nutella Cake",
    category: "cake",
    price: 18.9,
    img: "./images/cheescake.jpg",
    desc: "Decadent Nutella cake with moist layers and a rich, irresistible chocolate-hazelnut taste.",
  },
  {
    id: 8,
    title: "Strawberry Milkshake",
    category: "Milkshake",
    price: 9.99,
    img: "./images/strawberry.jpg",
    desc: "Fresh strawberry milkshake made creamy and smooth with real berries in every sweet sip.",
  },
];
